"""Generate dist/gvon.user.js: a Tampermonkey/Violentmonkey fallback that hides blocklisted posts on x.com.

Why: the real filter is the mitmproxy addon (gvon/nullifier.py), which strips nullified posts before the
bytes reach the browser. Some people will not install a local CA; for them this userscript is the
"that div just doesn't appear" fallback. It is weaker: the posts are still downloaded, it only knows the
blocklist (no classifier, so no per-post text scoring), and it hides elements after X renders them.

It reads data/blocklist.json (written by gvon.label; only verdict=="block" accounts) and bakes the
usernames into the script, so re-run it after the blocklist changes. Nothing is fetched at runtime.

Usage:  .venv/bin/python scripts/gvon-userscript.py [--blocklist data/blocklist.json] [--out dist/gvon.user.js]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
USERNAME_RE = re.compile(r"^[A-Za-z0-9_]{1,50}$")  # X handle charset (15 max today; legacy handles longer)

TEMPLATE = r"""// ==UserScript==
// @name         GVON - Good Vibes Only Nullifier (blocklist fallback)
// @namespace    gvon
// @version      __VERSION__
// @description  Hides x.com posts from accounts on your local GVON blocklist (__COUNT__ accounts). Generated by scripts/gvon-userscript.py.
// @match        https://x.com/*
// @match        https://twitter.com/*
// @match        https://mobile.x.com/*
// @match        https://mobile.twitter.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

(function () {
  "use strict";
  // Lowercased usernames from data/blocklist.json at generation time (__GENERATED__).
  const BLOCKED = new Set(__USERNAMES__);
  const HANDLE = /^\/([A-Za-z0-9_]{1,50})\/?$/;

  // Every handle shown in the post's author rows (the post itself and any quoted post).
  function handlesIn(article) {
    const out = [];
    article.querySelectorAll('[data-testid="User-Name"] a[href]').forEach((a) => {
      const m = HANDLE.exec(a.getAttribute("href") || "");
      if (m) out.push(m[1].toLowerCase());
    });
    return out;
  }

  // X recycles DOM nodes while scrolling, so re-check every article on each mutation batch instead of
  // marking it "done" forever; a post that no longer matches is shown again.
  function check(article) {
    const hit = handlesIn(article).find((h) => BLOCKED.has(h));
    if (hit) {
      if (article.dataset.gvonHidden !== hit) {
        article.dataset.gvonHidden = hit;
        article.style.setProperty("display", "none", "important");
      }
    } else if (article.dataset.gvonHidden) {
      delete article.dataset.gvonHidden;
      article.style.removeProperty("display");
    }
  }

  function scan(root) {
    if (!root || !root.querySelectorAll) return;
    if (root.matches && root.matches('article[data-testid="tweet"]')) check(root);
    root.querySelectorAll('article[data-testid="tweet"]').forEach(check);
  }

  let queued = false;
  function schedule() {
    if (queued) return;
    queued = true;
    requestAnimationFrame(() => {
      queued = false;
      scan(document.body);
    });
  }

  function start() {
    scan(document.body);
    new MutationObserver(schedule).observe(document.body, {
      childList: true, subtree: true, attributes: true, attributeFilter: ["href"],
    });
  }

  if (document.body) start();
  else document.addEventListener("DOMContentLoaded", start, { once: true });
})();
"""


def load_usernames(path: Path) -> list[str]:
    """Valid, de-duplicated, lowercased usernames from the blocklist (invalid handles are skipped)."""
    data = json.loads(path.read_text() or "{}")
    names: set[str] = set()
    for acct in data.get("accounts") or []:
        if (acct or {}).get("platform", "x") != "x":  # Telegram entries never apply to x.com
            continue
        name = str((acct or {}).get("username") or "").strip().lstrip("@")
        if USERNAME_RE.match(name):
            names.add(name.lower())
        elif name:
            print(f"skipping invalid username in blocklist: {name!r}", file=sys.stderr)
    return sorted(names)


def render(usernames: list[str]) -> str:
    now = datetime.now(timezone.utc)
    return (TEMPLATE.replace("__USERNAMES__", json.dumps(usernames))
            .replace("__COUNT__", str(len(usernames)))
            .replace("__VERSION__", now.strftime("%Y.%m.%d.%H%M"))
            .replace("__GENERATED__", now.isoformat(timespec="seconds")))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--blocklist", type=Path, default=ROOT / "data" / "blocklist.json")
    ap.add_argument("--out", type=Path, default=ROOT / "dist" / "gvon.user.js")
    args = ap.parse_args(argv)
    if not args.blocklist.exists():
        print(f"{args.blocklist} not found; run `python -m gvon.label` first", file=sys.stderr)
        return 1
    usernames = load_usernames(args.blocklist)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(usernames))
    print(f"wrote {args.out} ({len(usernames)} blocked accounts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
